### ISSUE TITLE
Allow to set a custom port and/or path

### ISSUE THREAD

**Issue by ammannbe** [werty1st/Redirect-Click-n-Load#3]
I'm not sure if it makes sense but it would be nice if we could set a custom port (e.g. 443) and additional path.
With that it would make it possible to proxy requests without opening firewall rules.

I could make a PR if you want.

**Comment by werty1st** [comment]
you're welcome to do so :)

**Comment by dima0git** [comment]
I think this is a good idea. And I think it would solve the following problem:

I am using Dreamweaver for the development of web sites. And the live preview does not work, as long as the Click&Load Plugin is activated. Somehow it breaks the preview functionality.

I am getting only the message that a redirection error occurred.

**Comment by werty1st** [comment]
> I think this is a good idea. And I think it would solve the following problem:
> 
> I am using Dreamweaver for the development of web sites. And the live preview does not work, as long as the Click&Load Plugin is activated. Somehow it breaks the preview functionality.
> 
> I am getting only the message that a redirection error occurred.


Fixed with: https://github.com/werty1st/Redirect-Click-n-Load/commit/d3871a9fe5d8a80d85ffac56cda89c1453c7896f

**Comment by werty1st** [comment]
Fixed with: https://github.com/werty1st/Redirect-Click-n-Load/commit/8ef3fea19d48a202c7de4c51d7bc36e9faab7b9e

**Comment by dima0git** [comment]
> 
> 
> Fixed with: [8ef3fea](https://github.com/werty1st/Redirect-Click-n-Load/commit/8ef3fea19d48a202c7de4c51d7bc36e9faab7b9e)

Confirmed. Just tested. Thanks!
