### ISSUE TITLE
Plugin breaks Dreamweaver Live Preview Functionality

### ISSUE THREAD

**Issue by dima0git** [werty1st/Redirect-Click-n-Load#4]
I am using Dreamweaver for the development of web sites. And the live preview does not work, as long as the Click&Load Plugin is activated. Somehow it breaks the preview functionality.

I am getting only the message that a redirection error occurred and that the redirection was stopped, because otherwise in cannot end.

The port used by Dreamweaver is 60931.

**Comment by werty1st** [comment]
You can just Click on the Icon and the Plugin will be paused. Maybe  this helps already.

**Comment by werty1st** [comment]
duplicate

**Comment by dima0git** [comment]
Believe me, I tried to deactivate the add-on, but it still kills the Live Preview of Deamweaver. The only way to get it back to work was to disable or uninstall completely your add-on.

I think it blocks the above mentioned port or all ports on localhost...
