### ISSUE TITLE
Plugin blocks access to localhost 

### ISSUE THREAD

**Issue by foorschtbar** [werty1st/Redirect-Click-n-Load#5]
When Plugin is enabled, i cant access any service running on localhost. Looks like thee same problem as in #4. 

Why the filter in background.js Line39-40 doesnt use the JDownloader Port?
https://github.com/werty1st/Redirect-Click-n-Load/blob/7a14ca1a7374c51dffbaa10e4a4c06174f821f0a/background.js#L39

If u wish i can make a PR

**Comment by werty1st** [comment]
Its not allowed:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#invalid_match_patterns

**Comment by werty1st** [comment]
new version 1.3.1 should be online in a few hours
