### ISSUE TITLE
[Feature Request] Possibility to serve over TLS

### ISSUE THREAD

**Issue by tobidemski** [werty1st/Redirect-Click-n-Load#7]
Hey,

it would be nice if you can define if the request should go over https instead of http.
Would be nice to see the option in this extension. (Maybe we can set the hostname with https://?)

Best regards

**Comment by werty1st** [comment]
Hi,

i was able to use TLS without modifications by setting the port to 80 
![image](https://user-images.githubusercontent.com/4736160/143444522-fd6f0c86-78f8-4b7e-a128-d00a2e49af2f.png)
and a corresponding proxy rule:
![image](https://user-images.githubusercontent.com/4736160/143447996-ea1da50f-c0e7-458b-a9b4-0479bdf6cc38.png)


The request got redirected to https an then forwarded to pyload.
![image](https://user-images.githubusercontent.com/4736160/143445630-c4ac3b9f-9920-4d44-96cc-f8949d2de173.png)

**Comment by werty1st** [comment]
Anyway i added support to use https with basic auth.

If you setup a custom click'n'load subdomain like this:
![image](https://user-images.githubusercontent.com/4736160/143501557-c6dcbda0-4e05-4a0e-a7d5-3576e192f0c1.png)
you can use a public available domain with basic authentication.

**Comment by werty1st** [comment]
should be updated in a few hours. firefox version is already live:
https://addons.mozilla.org/en-US/firefox/addon/redirect-click-n-load/
