### ISSUE TITLE
no function with 1.4.0

### ISSUE THREAD

**Issue by bozzfozz** [werty1st/Redirect-Click-n-Load#8]
with the new version no longer works, regardless of whether it is chrome or firefox

I've tried many things that came to my mind so quickly

**Comment by werty1st** [comment]
Hi, can you test if it still works with the old version?
https://github.com/werty1st/Redirect-Click-n-Load/releases/download/1.3.1/redirect_clicknload-1.3.1-fx.xpi

I receive a lots of mixed content errors in the debug console. If i disable mixed-content-blocking it works like before.

Atm i think that it won't be possible to use non https targets anymore.

**Comment by werty1st** [comment]
If i switch back to version 1.3.1 i still have to disable this flag:
chrome://flags/#block-insecure-private-network-request
![image](https://user-images.githubusercontent.com/4736160/143585944-6a917dce-1361-4e38-8b65-73cdec3b2877.png)

otherwise chrome logs errors like this:

> Access to script at 'http://192.168.1.1:9666/jdcheck.js' (redirected from 'http://127.0.0.1:9666/jdcheck.js') from origin 'http://filecrypt.co' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.

**Comment by werty1st** [comment]
I don't think there is an easy solution. For the moment there are 3 Options you can chose from:

1. Allow mixed content: (if you load from http**s**://filecrypt.co/)
![image](https://user-images.githubusercontent.com/4736160/143586733-024440a5-2a40-4be1-b124-e995adabe882.png)

2. Allow  LAN access like here: (if you load from http://filecrypt.co/)
chrome://flags/#block-insecure-private-network-request
![image](https://user-images.githubusercontent.com/4736160/143585944-6a917dce-1361-4e38-8b65-73cdec3b2877.png)

3. Put a valid https in front of pyload's click'n'load server (thats what i do now)

**Comment by bozzfozz** [comment]
ok thank you this is how it worked
